services:
  database:
    image: postgres:13.4-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passweird
      - POSTGRES_DB=postgres
    volumes:
      - ./data/postgresdb:/var/lib/postgresql/data